=== arhouati/DB2EAV/src/db2eav/config/schema/eav-schema.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="Configuration">
	  <xs:complexType>
	    <xs:sequence>
	    
	      <xs:element name="EntityTable">
	      	 <xs:complexType>
	            <xs:attribute name="name" type="xs:string" use="required"/>
	      		<xs:attribute name="id" type="xs:string" use="required"/>
	      		<xs:attribute name="identifier" type="xs:string" use="required"/>
	      		<xs:attribute name="other" type="xs:string"/>
	        </xs:complexType>
	      </xs:element>
	      
	      <xs:element name="AttributeTable">
	      	<xs:complexType>
	      		<xs:attribute name="name" type="xs:string" use="required"/>
	      		<xs:attribute name="id" type="xs:string" use="required"/>
	      		<xs:attribute name="identifier" type="xs:string" use="required"/>
	      		<xs:attribute name="type" type="xs:string" use="required"/>
	      		<xs:attribute name="idEntity" type="xs:string" use="required"/>
	        </xs:complexType>
	      </xs:element>
	      
	      <xs:element name="ValueTable">
	      	<xs:complexType>
	          <xs:sequence maxOccurs="unbounded">
	            <xs:element name="customValueTable">
	            	<xs:complexType>
	            		<xs:attribute name="type" type="xs:string" use="required"/>
	            		<xs:attribute name="name" type="xs:string" use="required"/>
	      				<xs:attribute name="id" type="xs:string" use="required"/>
	      				<xs:attribute name="identifier" type="xs:string" use="required"/>
	      				<xs:attribute name="value" type="xs:string" use="required"/>
	      				<xs:attribute name="idContent" type="xs:string" use="required"/>
	            	</xs:complexType>
	            </xs:element>
	          </xs:sequence>
	        </xs:complexType>
	      </xs:element>
	      
	      <xs:element name="ContentTable">
	      	<xs:complexType>
	          	<xs:attribute name="name" type="xs:string" use="required"/>
	      		<xs:attribute name="id" type="xs:string" use="required"/>
	      		<xs:attribute name="identifier" type="xs:string" use="required"/>
	      		<xs:attribute name="idEntity" type="xs:string" use="required"/>
	        </xs:complexType>
	      </xs:element>
	      
	    </xs:sequence>
	  </xs:complexType>
	</xs:element>

	<xs:element name="TypeAttributes">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element name="type">
					<xs:complexType>
						<xs:attribute name="name" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
	        </xs:sequence>
	    </xs:complexType>
	</xs:element>
	
	</xs:sequence>
	        </xs:complexType>
	      </xs:element>
</xs:schema>

=== arhouati/DB2EAV/src/db2eav/config/eav-cms.config.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--  Todo: schema ddt -->

<Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/eav-schema.xsd">
	<!--  model EAV -->
	<EntityTable name="" id="" identifier="" other=""/>
	<AttributeTable name="" id="" identifier="" type="" idEntity="" />
	
	<!-- In definition you can use the field %type% and %identifier% of attribute -->
	<ValueTable>
		<customValueTable type="default" name="" id="" identifier="" value="" idContent="" />
	</ValueTable>
	
	<!-- Content Table -->
	<ContentTable name="" id="" identifier="" idEntity=""  />
	<TypeAttributes>
		<type name="" />
	</TypeAttributes>
</Configuration>

=== arhouati/DB2EAV/src/db2eav/config/eav-magento.config.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/eav-schema.xsd">
	<!--  model EAV -->
	<EntityTable name="eav_entity_type" identifier="entity_type_code" id="entity_type_id" />
	<AttributeTable name="eav_attribute" idEntity="entity_type_id" id="attribute_id" identifier="attribute_code" type="backend_type" />
	
	<!-- In definition you can use the field %type% and %identifier% of attribute -->
	<ValueTable>
		<customValueTable type="default" name="catalog_product_entity_text" id="attribute_id" identifier="value_id" value="value" idContent="entity_id" />
		<customValueTable type="datetime" name="catalog_product_entity_datetime" id="attribute_id" identifier="value_id" value="value" idContent="entity_id" />
		<customValueTable type="decimal" name="catalog_product_entity_decimal" id="attribute_id" identifier="value_id" value="value" idContent="entity_id" />
		<customValueTable type="gallery" name="catalog_product_entity_gallery" id="attribute_id" identifier="value_id" value="value" idContent="entity_id" />
		<customValueTable type="group_price" name="catalog_product_entity_group_price" id="attribute_id" identifier="value_id" value="value" idContent="entity_id" />
		<customValueTable type="media_gallery" name="catalog_product_entity_media_gallery" id="attribute_id" identifier="value_id" value="value" idContent="entity_id" />
		<customValueTable type="media_gallery_value" name="catalog_product_entity_media_gallery_value" id="attribute_id" identifier="value_id" value="value" idContent="entity_id" />
		<customValueTable type="tier_price" name="catalog_product_entity_tier_price" id="attribute_id" identifier="value_id" value="value" idContent="entity_id" />
		<customValueTable type="varchar" name="catalog_product_entity_varchar" id="attribute_id" identifier="value_id" value="value" idContent="entity_id" />
		<customValueTable type="int" name="catalog_product_int" id="attribute_id" identifier="value_id" value="value" idContent="entity_id" />	
	</ValueTable>
	
	<!-- Content Table -->
	<ContentTable name="catalog_product_entity" idEntity="entity_type_id" id="entity_id" identifier="sku" />
	
	<!-- Type Attributes Table -->
	<TypeAttributes>
		<type name="default" />
		<type name="mgdate" />
		<type name="mgdatetime" />
		<type name="mginteger" />
		<type name="mgfloat" />
		<type name="mgtime" />
		<type name="mgsrrating" />
		<type name="mgcomcomments"/>
	</TypeAttributes>
</Configuration>

=== arhouati/DB2EAV/src/db2eav/config/eav-drupal.config.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/eav-schema.xsd">
	<!--  model EAV -->
	<EntityTable name="node_type" id="type" identifier="name" />
	<AttributeTable name="field_config_instance" id="bundle" identifier="field_name" type="field_name" idEntity="bundle" />
	
	<!-- In definition you can use the field %type% and %identifier% of attribute -->
	<ValueTable>
		<customValueTable type="default" name="field_data_%type%" id="bundle" identifier="bundle" value="%type%_value" idContent="entity_id" />
	</ValueTable>
	
	<!-- Content Table -->
	<ContentTable name="node" id="nid" identifier="title" idEntity="type"  />
	<!-- Type Attributes Table -->
	<TypeAttributes>
		<type name="default" />
		<type name="drdate" />
		<type name="drdatetime" />
		<type name="drinteger" />
		<type name="drfloat" />
		<type name="drtime" />
		<type name="drsrrating" />
		<type name="drcomcomments"/>
	</TypeAttributes>
</Configuration>

=== arhouati/DB2EAV/src/db2eav/config/eav-ezpublish.config.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/eav-schema.xsd">
	<!--  model EAV -->
	<EntityTable name="ezcontentclass" id="id" identifier="identifier" other="version,remote_id"/>
	<AttributeTable name="ezcontentclass_attribute" id="id" identifier="identifier" type="data_type_string" idEntity="contentclass_id" />
	
	<!-- In definition you can use the field %type% and %identifier% of attribute -->
	<ValueTable>
		<customValueTable type="default"  name="ezcontentobject_attribute" id="contentclassattribute_id" identifier="id" value="data_text" idContent="contentobject_id" />
		<customValueTable type="ezdate" name="ezcontentobject_attribute" id="contentclassattribute_id" identifier="id" value="data_int" idContent="contentobject_id" />
		<customValueTable type="ezdatetime"  name="ezcontentobject_attribute" id="contentclassattribute_id" identifier="id" value="data_int" idContent="contentobject_id" />
		<customValueTable type="ezinteger"  name="ezcontentobject_attribute" id="contentclassattribute_id" identifier="id" value="data_int" idContent="contentobject_id" />
		<customValueTable type="ezfloat"  name="ezcontentobject_attribute" id="contentclassattribute_id" identifier="id" value="data_float" idContent="contentobject_id" />
		<customValueTable type="eztime"  name="ezcontentobject_attribute" id="contentclassattribute_id" identifier="id" value="data_int" idContent="contentobject_id" />
		<customValueTable type="ezsrrating"  name="ezcontentobject_attribute" id="contentclassattribute_id" identifier="id" value="data_int" idContent="contentobject_id" />
		<customValueTable type="ezcomcomments"  name="ezcontentobject_attribute" id="contentclassattribute_id" identifier="id" value="data_int" idContent="contentobject_id" />
	</ValueTable>
	
	<!-- Content Table -->
	<ContentTable name="ezcontentobject" id="id" identifier="name" idEntity="contentclass_id"  />
	
	<!-- Type Attributes Table-->
	<TypeAttributes>
		<type name="default"  />
		<type name="ezdate"  />
		<type name="ezdatetime"/>
		<type name="ezinteger" />
		<type name="ezfloat" />
		<type name="eztime" />
		<type name="ezsrrating" />
		<type name="ezcomcomments"/>
		<type name="ezstring" />
		<type name="eztext"/>
		<type name="ezuser" />
		<type name="ezkeyword"/>
		<type name="ezpage"/>
		<type name="ezboolean"/>
		<type name="ezxmltext"/>
		<type name="ezinisetting"/>
		<type name="ezimage"/>
		<type name="ezpackage"/>
		<type name="ezurl"/>
		<type name="ezprice"/>
		<type name="ezmultioption"/>
		<type name="ezbinaryfile"/>
		<type name="ezselection"/>
	</TypeAttributes>
</Configuration>
